### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by TysonNgo** [TysonNgo/Keyboard-Sound-Maker#1]
### QT GUI (maybe?)

- [ ] browse for keyboard sound directory

- [ ] select audio output device

- [ ] show some type of feedback so that user knows it is working

    - [ ] one for keypress/keyrelease; a single icon to represent idle, key holding, key releasing

    - [ ] one for sound play; maybe a bar that changes size based on decibels
